config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about' => 'pages#about'
  get 'contacts' => 'pages#conatcts'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Omrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "Home", root_path %>
    <%= link_to "About", about_path%>
    <%= link_to "contacts", contacts_path%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About me</h1>
<p>Getting use to rails!!</p>

app/views/pages/conatcts.html.erb
<h1>Contact me</h1>
<p>9199312129</p>

app/views/pages/home.html.erb
<h1>Welcome to my first rails app</h1>
<p>I am creating an end to end application and learning about it in details!!</p>
<p>sign up here</p>